[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lanlan3292_python_screenshot_web"
version = "0.0.11"
description = "A Python tool for capturing safe webpage screenshots using Playwright."
readme = "README.md"
authors = [
    { name = "lanlan3292" }
]
requires-python = ">=3.8"
dependencies = [
    "playwright>=1.40.0",
]

[project.urls]
Home = "https://github.com/lanlan3292/lanlan3292_python_screenshot_web"